CREATE PROCEDURE [dbo].[RetrieveProperties]
	@StartDate DateTime,
	@EndDate DateTime
AS
BEGIN
	SELECT [PropertyCode]
      ,[AirBnBHomeName]
      ,[Address]
      ,[PropertyStatus]
      ,[Vertical]
      ,[Owner]
      ,[NeedsOwnerApproval]
      ,[ListingStartDate]
      ,[StreamlineHomeName]
      ,[StreamlineUnitID]
      ,[Account]
      ,[City]
      ,[Market]
      ,[State]
      ,[Area]
      ,[Neighborhood]
      ,[BookingGuidelines]
      ,[Floor]
      ,[Bedrooms]
      ,[Bathrooms]
      ,[BedsDescription]
      ,[MaxOcc]
      ,[StdOcc]
      ,[Elevator]
      ,[A_C]
      ,[Parking]
      ,[WiFiNetwork]
      ,[WiFiPassword]
      ,[Ownership]
      ,[MonthlyRent]
      ,[DailyRent]
      ,[CleaningFees]
      ,[AIrBnBID]
      ,[AirbnbiCalexportlink]
      ,[Amenities]
      ,[Zipcode]
      ,[OldListingTitle]
      ,[GoogleDrivePicturesLink]
      ,[SquareFootage]
      ,[Password]
      ,[InquiryLeadApproval]
      ,[RevTeam2xApproval]
      ,[PendingContractDate]
      ,[PendingOnboardingDate]
      ,[SecurityDeposit]
      ,[Pool]
      ,[AirBnb]
      ,[FlipKey]
      ,[Expedia]
      ,[Inactive]
      ,[Currency]
      ,[CrossStreets]
      ,[SellingPoints]
      ,[CheckInType]
      ,[HomeAway]
      ,[BeltDesignation]
	  ,[ManagementFee]
	  ,[OutstandingBalance]
	  ,[OwnerEntity]
	  ,[OwnerPayout]
	  ,[PaymentEmail]
      ,[CreatedDate]
      ,[CreatedBy]
      ,[ModifiedDate]
      ,[ModifiedBy]
	  ,[Dead]
FROM [dbo].[CPL] p
WHERE ((CONVERT(date, dateadd(HOUR, -8, p.[CreatedDate])) >= @StartDate and CONVERT(date, dateadd(HOUR, -8, p.[CreatedDate])) <= @EndDate) or p.[CreatedDate] is null)
ORDER BY p.[CreatedDate] desc, p.[PropertyCode]
END
